### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by shubhamoy**

### CODE REVIEW

**Comment by webmakaka** [comment]
Hi! Something not works on original project?

**Comment by shubhamoy** [comment]
There has been a syntax change in multer after version upgrade. Check this https://github.com/expressjs/multer/issues/169

**Comment by sysadm-ru** [comment]
I'm using on this project multer 0.1.8
$ npm install --save multer@0.1.8

**Comment by webmakaka** [comment]
I'm using on this project multer 0.1.8
$ npm install --save multer@0.1.8

**Pull request closed without merging**
